# default settings
title:       sinius x blog
author:      sinius
description: 'It''s Now or Never'
baseurl:     ''
url:         "http://sinius.net"

# settings
markdown: redcarpet
redcarpet:
    extensions:
      - no_intra_emphasis
      - tables
      - fenced_code_blocks
      - autolink
      - strikethrough
      - superscript
      - hard_wrap
      - with_toc_data
highlighter: pygments
permalink:   pretty
paginate:    5
sass:
  compressed: true

# optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# plugins
plugin:
  disqus: sinius
  google_analytics: UA-49088218-1

# links
link:
  github: siniusxcode
  linkedin: sinius
  email: sinius@gmail.com
  feedburner: sinius